import random
import os
import copy
import json
import warnings
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional, Type, Any, List, Dict

import numpy as np
import yaml
import lz4.frame
import gymnasium as gym

from poke_env import (
    AccountConfiguration,
    LocalhostServerConfiguration,
)
from poke_env.environment import Battle
from poke_env.player import OpenAIGymEnv, Player
from poke_env.teambuilder import Teambuilder
from poke_env.ps_client.server_configuration import ServerConfiguration

import metamon
from metamon.config import format_for_agent
from metamon.interface import (
    UniversalState,
    UniversalAction,
    RewardFunction,
    ObservationSpace,
    ActionSpace,
)
from metamon.data import DATA_PATH
from metamon.data.download import download_teams
from metamon.env.metamon_player import MetamonPlayer, PokeAgentPlayer
from metamon.backend.team_prediction.team_index import (
    load_team_files,
    resolve_format_dir,
)

METAMON_TEAM_SETS = {
    "competitive",  # human-made sample teams, usually from the Smogon forums
    "modern_replays",  # predicted teams based on recent replays using the best prediction strategy we have available for each generation
    "modern_replays_v2",  # an updated/expanded version of modern_replays (September 2025) that was verified against the PokéAgent Challenge server's frozen teambuilder rules
    "paper_replays",  # predicted teams from replays. backwards compatible with a team set mentioned in the paper
    "paper_variety",  # procedurally generated teams with unrealistic OOD lead-off Pokémon. Movesets were generated by sampling from all-time usage stats.
    "gl_05_26",  # general ladder May 2026 — last-year revealed teams, NaiveUsagePredictor fill
    "hl_05_26",  # high ladder May 2026 — 1400+ (1600+ gen9) ∪ smogtours
}


class TeamSet(Teambuilder):
    """Sample from a directory of Showdown team files.

    A simple wrapper around poke-env's Teambuilder that randomly samples a team from a
    directory of team files.

    Args:
        team_file_dir: The directory containing the team files (searched recursively).
            Team files are just text files in the standard Showdown export format. See
            https://pokepast.es/syntax.html for details.
        battle_format: The battle format of the team files (e.g. "gen1ou", "gen2ubers",
            etc.). Note that we assume files have a matching extension (e.g.
            "any_name.gen1ou_team").
    """

    def __init__(self, team_file_dir: str, battle_format: str):
        super().__init__()
        self.team_file_dir = team_file_dir
        self.battle_format = format_for_agent(battle_format)
        self.format_dir = str(resolve_format_dir(team_file_dir, self.battle_format))
        self.team_files, loaded_from_index = load_team_files(
            team_file_dir, self.battle_format
        )
        if loaded_from_index:
            print(f"loaded {len(self.team_files):,} teams from TeamSet index")
        else:
            print(f"Found {len(self.team_files):,} teams in TeamSet")
        self._most_recent_team_file = None

    def block_team(self, packed_team: str) -> bool:
        """
        Reject True to reject the team and resample.

        Override to quick-fix team selection in the event of minor rule changes.

        Args:
            packed_team: Showdown team string in the "packed" format (e.g. Brambleghast||lifeorb|windrider|poltergeist|...)

        Returns:
            bool: True to reject the team and resample.
        """
        return False

    @property
    def most_recent_team_file(self) -> Optional[str]:
        return self._most_recent_team_file

    def yield_team(self) -> str:
        for attempt in range(100):
            # read team from disk
            file = random.choice(self.team_files)
            self._most_recent_team_file = file
            with open(file, "r") as f:
                team_data = f.read()
            # check team
            parsed = self.parse_showdown_team(team_data)
            candidate_team = self.join_team(parsed)
            if not self.block_team(candidate_team):
                return candidate_team
            if attempt % 10 == 0:
                warnings.warn(f"Failed to find valid team after {attempt + 1} attempts")
        raise RuntimeError(f"Could not find valid team after 100 attempts")


class PokeAgentTeamSet(TeamSet):
    """
    The PokéAgent Challenge uses the June 2025 Showdown rules with bans on Zoroark/Zorua and Revival Blessing.

    This is a hot-patch to remove zoroark/zorua and revival blessing from summer 2025 procedurally generated teamsets
    """

    def block_team(self, packed_team: str) -> bool:
        if self.battle_format == "gen9ou":
            packed_team_lower = packed_team.lower()
            if "zoroark" in packed_team_lower or "zorua" in packed_team_lower:
                return True
            elif "revivalblessing" in packed_team_lower:
                return True
        return False


class EpochRef:
    """Mutable shared epoch counter for schedule-aware team sets.

    A tiny mutable container so the experiment loop can bump the current epoch
    once per collection cycle and every :class:`WeightedMixedTeamSet` that holds
    a reference to the same ``EpochRef`` sees the update lazily on its next
    ``yield_team()`` call — no need to reach into the env tree from the
    experiment.
    """

    __slots__ = ("epoch",)

    def __init__(self, epoch: int = 0):
        self.epoch = epoch


class TeamMixSchedule:
    """A time-varying team-mix schedule parsed from a YAML file.

    The YAML has a top-level ``schedule`` list of entries, each with an
    ``epoch`` boundary and a ``weights`` mapping of ``set_name -> weight``::

        schedule:
          - epoch: 0
            weights:
              gl_05_26: 1.0
              smogon_pass2: 0.0
              smogon_pass2_selected: 0.0
          - epoch: 920
            weights:
              gl_05_26: 0.75
              smogon_pass2: 0.15
              smogon_pass2_selected: 0.10
          ...

    At runtime, :meth:`weights_for_epoch` returns the weights of the latest
    entry whose ``epoch`` is <= the current epoch. All ``weights`` mappings must
    share the same set of keys (the component team sets); their order is fixed
    by the first entry.
    """

    def __init__(self, entries: List[Dict[str, Any]], *, source: str = "?"):
        if not entries:
            raise ValueError("TeamMixSchedule: empty schedule")
        # Sort by epoch boundary (ascending).
        entries = sorted(entries, key=lambda e: e["epoch"])
        self._epochs: List[int] = [e["epoch"] for e in entries]
        # Determine the canonical set-name order from the first entry.
        first_weights = entries[0]["weights"]
        self._set_names: List[str] = list(first_weights.keys())
        # Validate all entries share the same keys, then store weight lists in
        # canonical order.
        self._weight_rows: List[List[float]] = []
        for e in entries:
            w = e["weights"]
            if set(w.keys()) != set(self._set_names):
                raise ValueError(
                    f"TeamMixSchedule: entry at epoch {e['epoch']} has keys "
                    f"{sorted(w.keys())}, expected {sorted(self._set_names)} "
                    f"(must match the first entry)"
                )
            self._weight_rows.append([float(w[n]) for n in self._set_names])
        self._source = source

    # -- lookups -----------------------------------------------------------

    @property
    def set_names(self) -> List[str]:
        """Ordered component team-set names (from the first schedule entry)."""
        return list(self._set_names)

    @property
    def source(self) -> str:
        return self._source

    def weights_for_epoch(self, epoch: int) -> Dict[str, float]:
        """Return the active ``{set_name: weight}`` dict for ``epoch``.

        Selects the latest entry with ``entry.epoch <= epoch``. If ``epoch`` is
        before the first boundary, the first entry is used.
        """
        idx = 0
        for i, boundary in enumerate(self._epochs):
            if boundary <= epoch:
                idx = i
            else:
                break
        row = self._weight_rows[idx]
        return dict(zip(self._set_names, row))

    def initial_weights(self) -> List[float]:
        """Return the weights at epoch 0 (the first entry's weight row)."""
        return list(self._weight_rows[0])

    def describe(self) -> str:
        """Human-readable one-line summary of the phase boundaries."""
        parts = []
        for boundary, row in zip(self._epochs, self._weight_rows):
            w = dict(zip(self._set_names, row))
            parts.append(
                f"e{boundary}: " + ",".join(f"{k}={v:.0%}" for k, v in w.items())
            )
        return " | ".join(parts)

    # -- construction ------------------------------------------------------

    @classmethod
    def from_yaml_file(cls, path: str) -> "TeamMixSchedule":
        """Parse a schedule YAML file."""
        with open(path, "r") as f:
            raw = yaml.safe_load(f)
        if not isinstance(raw, dict) or "schedule" not in raw:
            raise ValueError(
                f"TeamMixSchedule: {path!r} must have a top-level 'schedule' list"
            )
        entries = raw["schedule"]
        if not isinstance(entries, list) or not entries:
            raise ValueError(
                f"TeamMixSchedule: 'schedule' in {path!r} must be a non-empty list"
            )
        # Normalize entries: ensure 'epoch' (int) and 'weights' (dict) keys.
        normalized = []
        for e in entries:
            if "epoch" not in e or "weights" not in e:
                raise ValueError(
                    f"TeamMixSchedule: each entry needs 'epoch' and 'weights'; "
                    f"got {e!r} in {path!r}"
                )
            normalized.append({"epoch": int(e["epoch"]), "weights": dict(e["weights"])})
        return cls(normalized, source=path)


class WeightedMixedTeamSet(TeamSet):
    """Sample teams from multiple underlying TeamSets with configurable weights.

    Unlike a merged directory (which fixes the sampling ratio by file count and
    wastes disk duplicating small sets), this holds N ``TeamSet`` objects and
    picks one per battle according to ``weights``. Each underlying TeamSet then
    does its own uniform ``yield_team()`` draw.

    Used to build a curriculum mix of, e.g., a broad-ladder set
    (``gl_05_26``) and competitive sets (``smogon_pass2`` /
    ``smogon_pass2_selected``) without duplicating team files. The mix ratio is
    set at construction time and can be changed on each run restart via a mix
    spec string (see :func:`parse_team_mix_spec`), or varied automatically over
    training epochs by attaching a :class:`TeamMixSchedule` + :class:`EpochRef`
    (see :func:`get_metamon_team_set_from_schedule`).

    Args:
        team_sets: List of ``TeamSet`` objects to mix.
        weights:   Per-set sampling weights (need not sum to 1; normalized
                   internally). Must be the same length as ``team_sets``.
        schedule:  Optional :class:`TeamMixSchedule` for epoch-driven weight
                   updates. When set, ``yield_team`` lazily refreshes weights
                   from the schedule whenever ``epoch_ref.epoch`` changes.
        epoch_ref: Optional shared :class:`EpochRef`. Required when ``schedule``
                   is set; ignored otherwise.
    """

    def __init__(
        self,
        team_sets: List[TeamSet],
        weights: List[float],
        schedule: Optional[TeamMixSchedule] = None,
        epoch_ref: Optional[EpochRef] = None,
    ):
        # Deliberately skip TeamSet.__init__ (which scans a single directory).
        # We still need Teambuilder.__init__ for poke-env's team parsing.
        Teambuilder.__init__(self)
        if len(team_sets) != len(weights):
            raise ValueError("team_sets and weights must have equal length")
        if not team_sets:
            raise ValueError("WeightedMixedTeamSet requires at least one TeamSet")
        total = sum(weights)
        if total <= 0:
            raise ValueError("Weights must sum to a positive value")
        self.team_sets = team_sets
        self.battle_format = team_sets[0].battle_format
        self._most_recent_team_file = None
        # Schedule-driven auto-update state.
        self._schedule: Optional[TeamMixSchedule] = schedule
        self._epoch_ref: Optional[EpochRef] = epoch_ref
        self._last_epoch: int = -1
        if schedule is not None:
            if epoch_ref is None:
                raise ValueError("epoch_ref is required when schedule is set")
            # Validate that the schedule's set names match the provided team sets.
            sched_names = schedule.set_names
            if len(sched_names) != len(team_sets):
                raise ValueError(
                    f"Schedule has {len(sched_names)} component sets "
                    f"({sched_names}) but {len(team_sets)} team_sets were provided"
                )
            self._apply_schedule_weights()  # sets self.weights + self._last_epoch
        else:
            self.weights = [w / total for w in weights]
        self._log_weights()

    def _log_weights(self) -> None:
        names = [getattr(ts, "team_file_dir", "?") for ts in self.team_sets]
        print(
            "WeightedMixedTeamSet: "
            + ", ".join(f"{n}={w:.0%}" for n, w in zip(names, self.weights))
        )

    def _apply_schedule_weights(self) -> None:
        """Refresh ``self.weights`` from the schedule for ``epoch_ref.epoch``."""
        assert self._schedule is not None and self._epoch_ref is not None
        epoch = self._epoch_ref.epoch
        w_dict = self._schedule.weights_for_epoch(epoch)
        # Map schedule set names to the positional order of self.team_sets.
        # (team_sets are constructed in schedule.set_names order, so they align.)
        raw = [w_dict.get(name, 0.0) for name in self._schedule.set_names]
        total = sum(raw)
        if total <= 0:
            raise ValueError(f"TeamMixSchedule at epoch {epoch} has all-zero weights")
        self.weights = [w / total for w in raw]
        self._last_epoch = epoch

    def set_weights(self, weights: List[float]) -> None:
        """Manually update the sampling weights (normalized internally)."""
        total = sum(weights)
        if total <= 0:
            raise ValueError("Weights must sum to a positive value")
        self.weights = [w / total for w in weights]
        self._log_weights()

    @property
    def most_recent_team_file(self) -> Optional[str]:
        return self._most_recent_team_file

    def yield_team(self) -> str:
        # Lazy schedule refresh + weighted component pick, delegated to
        # ``sample_component_index`` so callers that need to couple both sides
        # to the same component can reuse the identical draw logic.
        idx = self.sample_component_index()
        return self.yield_team_from_component(idx)

    def sample_component_index(self) -> int:
        """Pick a component index per the current weights (schedule-refreshed).

        Performs the lazy schedule refresh (one int comparison per draw; weight
        recompute only on epoch change) and then samples one component index.
        Factored out of :meth:`yield_team` so a caller can sample one index and
        then draw *both* players' teams from the same component via
        :meth:`yield_team_from_component` — keeping both sides on the same team
        pool per battle (no composition mismatch).
        """
        if self._schedule is not None and self._epoch_ref is not None:
            if self._epoch_ref.epoch != self._last_epoch:
                self._apply_schedule_weights()
                self._log_weights()
        return random.choices(range(len(self.team_sets)), weights=self.weights)[0]

    def yield_team_from_component(self, idx: int) -> str:
        """Draw a team from a specific component (no weighted pick).

        ``idx`` should come from :meth:`sample_component_index` (or be located
        via :meth:`index_for_team_file_dir`). Sets
        ``most_recent_team_file`` to the chosen component's file, exactly like
        :meth:`yield_team`, so the ``_ts-`` teamset token in trajectory
        filenames records the real component drawn.
        """
        chosen = self.team_sets[idx]
        team = chosen.yield_team()
        self._most_recent_team_file = chosen.most_recent_team_file
        return team

    def index_for_team_file_dir(self, team_file_dir: Optional[str]) -> Optional[int]:
        """Return the component index whose ``team_file_dir`` matches the arg.

        Used to couple two team sets to the same pool: when one side is a plain
        :class:`TeamSet` (pinned to one set, e.g. ``team_set: smogon_pass2``)
        and the other is this mix, the mix can draw from the component whose
        directory matches the plain side's, so both share the pool. Returns
        ``None`` when no component matches (the plain side's set is not one of
        this mix's components).
        """
        if team_file_dir is None:
            return None
        for idx, ts in enumerate(self.team_sets):
            if getattr(ts, "team_file_dir", None) == team_file_dir:
                return idx
        return None

    def block_team(self, packed_team: str) -> bool:
        return any(ts.block_team(packed_team) for ts in self.team_sets)


def parse_team_mix_spec(spec: str) -> List[tuple]:
    """Parse a team-mix spec string into ``(set_name, weight)`` pairs.

    Format: ``"set_name:weight,set_name:weight,..."``
    e.g. ``"gl_05_26:0.45,smogon_pass2:0.35,smogon_pass2_selected:0.20"``.
    Weights need not sum to 1 (normalized by the caller). Whitespace is tolerated.

    Raises:
        ValueError: on malformed entries, empty names, non-numeric weights, or
            negative weights.
    """
    parts = [p.strip() for p in spec.split(",") if p.strip()]
    if not parts:
        raise ValueError(f"Empty team mix spec: {spec!r}")
    pairs = []
    for part in parts:
        if ":" not in part:
            raise ValueError(
                f"Invalid team mix entry {part!r} in spec {spec!r}: "
                f"expected 'set_name:weight'"
            )
        name, _, weight_str = part.partition(":")
        name = name.strip()
        weight_str = weight_str.strip()
        if not name:
            raise ValueError(f"Empty set name in team mix entry {part!r}")
        try:
            weight = float(weight_str)
        except ValueError:
            raise ValueError(
                f"Invalid weight {weight_str!r} in team mix entry {part!r}"
            )
        if weight < 0:
            raise ValueError(f"Negative weight in team mix entry {part!r}")
        pairs.append((name, weight))
    return pairs


def is_team_mix_spec(name: str) -> bool:
    """Return True if ``name`` looks like a team-mix spec (contains a colon).

    Regular team-set names (e.g. ``gl_05_26``, ``competitive``) never contain
    colons, so this is a safe discriminator for dispatch.
    """
    return ":" in name


def get_metamon_team_mix(
    battle_format: str, spec: str, set_type: Type[TeamSet] = TeamSet
) -> WeightedMixedTeamSet:
    """Build a :class:`WeightedMixedTeamSet` from a mix spec string.

    Args:
        battle_format: Passed through to each underlying TeamSet.
        spec: Mix spec string (see :func:`parse_team_mix_spec`).
        set_type: TeamSet subclass to use for each component (default TeamSet).
    """
    pairs = parse_team_mix_spec(spec)
    team_sets = [get_metamon_teams(battle_format, name, set_type) for name, _ in pairs]
    weights = [w for _, w in pairs]
    return WeightedMixedTeamSet(team_sets=team_sets, weights=weights)


def get_metamon_team_set_or_mix(
    battle_format: str, name_or_spec: str, set_type: Type[TeamSet] = TeamSet
) -> TeamSet:
    """Resolve a team set by name, or a weighted mix if ``name_or_spec`` is a mix spec.

    Dispatches on :func:`is_team_mix_spec`: a string containing ``":"`` is
    treated as a mix spec (see :func:`parse_team_mix_spec`); anything else is a
    plain set name resolved via :func:`get_metamon_teams`.
    """
    if is_team_mix_spec(name_or_spec):
        return get_metamon_team_mix(battle_format, name_or_spec, set_type)
    return get_metamon_teams(battle_format, name_or_spec, set_type)


def get_metamon_team_set_from_schedule(
    battle_format: str, schedule: TeamMixSchedule, epoch_ref: EpochRef
) -> WeightedMixedTeamSet:
    """Build a schedule-aware :class:`WeightedMixedTeamSet`.

    The component TeamSets are loaded in ``schedule.set_names`` order, and the
    initial weights come from the schedule's epoch-0 entry. The returned team
    set lazily updates its weights on each ``yield_team()`` call whenever
    ``epoch_ref.epoch`` advances — no restart needed to shift the mix.
    """
    set_names = schedule.set_names
    team_sets = [get_metamon_teams(battle_format, name) for name in set_names]
    return WeightedMixedTeamSet(
        team_sets=team_sets,
        weights=schedule.initial_weights(),
        schedule=schedule,
        epoch_ref=epoch_ref,
    )


def get_metamon_teams(
    battle_format: str, set_name: str, set_type: Type[TeamSet] = TeamSet
) -> TeamSet:
    """
    Download a set of teams from huggingface (if necessary) and return a TeamSet.

    Args:
        battle_format: The battle format of the team files (e.g. "gen1ou", "gen2ubers", etc.).
            Showdown variants (e.g. PokéAgent's "gen1oulongtimer") are normalized automatically.
        set_name: The name of the set of teams to download. See the README for options. If a custom name is provided,
            we will search the `METAMON_CACHE_DIR` for a custom team set with that name.
        set_type: The type of TeamSet to return. Defaults to TeamSet.
    """
    fmt = format_for_agent(battle_format)
    if set_name in METAMON_TEAM_SETS:
        path = download_teams(fmt, set_name=set_name)
    elif metamon.METAMON_CACHE_DIR is not None:
        path = os.path.join(metamon.METAMON_CACHE_DIR, "teams", set_name)
    else:
        raise ValueError(f"`METAMON_CACHE_DIR` environment variable is not set!")
    if not os.path.exists(path):
        raise ValueError(
            f"Cannot locate valid team directory for format {fmt} at path {path}"
        )
    return set_type(path, fmt)


def _check_avatar(avatar: str):
    if avatar is None:
        return
    with open(os.path.join(DATA_PATH, "avatar_names.txt"), "r") as f:
        options = [l.strip() for l in f.readlines()]
    if avatar not in options:
        raise ValueError(
            f"Avatar {avatar} is not valid. See https://play.pokemonshowdown.com/sprites/trainers/ for a list of options."
        )
    else:
        return avatar


class PokeEnvWrapper(OpenAIGymEnv):
    """A thin wrapper around poke-env's OpenAIGymEnv that handles the observation space,
    action space, and reward function while adding some basic conveniences.

    Args:
        battle_format: The battle format of the team files (e.g. "gen1ou", "gen2ubers",
            etc.).
        observation_space: The observation space to use. Must be an instance of
            `interface.ObservationSpace`.
        reward_function: The reward function to use. Must be an instance of
            `interface.RewardFunction`.
        player_team_set: The team set to use for the player. Must be an instance of
            `TeamSet` or a poke-env TeamBuilder.
        opponent_type: The type of opponent to use. Must be a callable that creates a
            `poke_env.player.Player`. All the `metamon.baselines` implement this.
        opponent_team_set: The team set to use for the opponent. Must be an instance of
            `TeamSet` or a poke-env TeamBuilder. If the opponent set is not specified,
            the opponent plays with the same team set (but an independently sampled team)
            as the player.
        player_username: The username to use for the player. If not specified, a random
            username will be generated. It is important for this to be unique across
            parallel environments.
        player_password: The password to use for the player. This is usually not needed
            on the local server.
        opponent_username: The username to use for the opponent. If not specified, a
            random username will be generated. It is important for this to be unique
            across parallel environments.
        player_avatar: The avatar for the player when viewing battles in your browser.
            See https://play.pokemonshowdown.com/sprites/trainers/ for a list of
            options.
        opponent_avatar: The avatar for the opponent when viewing battles in your
            browser. See https://play.pokemonshowdown.com/sprites/trainers/ for a list
            of options.
        start_challenging: Whether to start challenging the opponent immediately. This
            is a poke-env detail handled by the other wrappers.
        start_timer_on_battle_start: Start the time increment controls that prevent
            infinite battles from inactive players.
        turn_limit: The maximum number of turns in a battle. Note that Showdown already
            enforces a limit of 1000 regardless of this setting.
        save_trajectories_to: The directory to save the trajectories to. Data is saved
            in the same format as the parsed replay dataset.
        save_results_to: Directory to write per-battle result logs. Data is saved in
            a CSV file with columns: Player Username, Team File, Opponent Username,
            Result, Turn Count, Battle ID.
        battle_backend: The Showdown state parsing backend. Options are 'poke-env' or
            'metamon'.
        team_preview_model: Optional TeamPreviewModel to use for predicting leads during
            team preview. Only works with battle_backend='metamon'. If None, uses random
            team preview selection.
    """

    _INIT_RETRIES = 250

    def __init__(
        self,
        battle_format: str,
        observation_space: ObservationSpace,
        action_space: ActionSpace,
        reward_function: RewardFunction,
        player_team_set: TeamSet,
        opponent_type: Optional[Type[Player]] = None,
        opponent_team_set: Optional[TeamSet] = None,
        player_username: Optional[str] = None,
        player_password: Optional[str] = None,
        opponent_username: Optional[str] = None,
        player_avatar: Optional[str] = None,
        opponent_avatar: Optional[str] = None,
        start_challenging: bool = True,
        start_timer_on_battle_start: bool = False,
        turn_limit: int = 1000,
        save_trajectories_to: Optional[str] = None,
        save_results_to: Optional[str] = None,
        battle_backend: str = "metamon",
        team_preview_model=None,
    ):
        if opponent_team_set is None or opponent_team_set is player_team_set:
            opponent_team_set = copy.deepcopy(player_team_set)
        random_username = (
            lambda: f"MM-{''.join(str(random.randint(0, 9)) for _ in range(10))}"
        )
        self.player_username = player_username or random_username()
        self.opponent_username = opponent_username or random_username()

        player_account_configuration = AccountConfiguration(
            self.player_username, player_password
        )
        opponent_account_configuration = AccountConfiguration(
            self.opponent_username, None
        )
        if save_trajectories_to is not None:
            self.save_trajectories_to = os.path.join(
                save_trajectories_to, battle_format
            )
            os.makedirs(self.save_trajectories_to, exist_ok=True)
        else:
            self.save_trajectories_to = None

        if save_results_to is not None:
            os.makedirs(save_results_to, exist_ok=True)
            self.save_results_to = os.path.join(
                save_results_to,
                f"battle_log_{self.player_username}_{battle_format}.csv",
            )
            if not os.path.exists(self.save_results_to):
                with open(self.save_results_to, "a") as f:
                    f.write(
                        "Player Username, Team File, Opponent Username, Result, Turn Count, Battle ID\n"
                    )
        else:
            self.save_results_to = None

        if opponent_type is not None:
            self.metamon_opponent_name = opponent_type.__name__
            self._current_opponent = opponent_type(
                battle_format=battle_format,
                team=opponent_team_set,
                account_configuration=opponent_account_configuration,
                server_configuration=self.server_configuration,
                avatar=_check_avatar(opponent_avatar),
                ping_timeout=None,
            )
        else:
            self._current_opponent = None
            self.metamon_opponent_name = None

        self.reward_function = copy.deepcopy(reward_function)
        self.metamon_obs_space = copy.deepcopy(observation_space)
        self.metamon_action_space = copy.deepcopy(action_space)
        self.metamon_team_set = player_team_set
        self.turn_limit = turn_limit
        self.metamon_battle_format = battle_format

        if battle_backend == "poke-env":
            player_class = Player
            # Warn if team preview model is provided with poke-env backend
            if team_preview_model is not None:
                warnings.warn(
                    "team_preview_model is only supported with battle_backend='metamon'. "
                    "The model will be ignored with battle_backend='poke-env'."
                )
        elif battle_backend == "metamon":
            player_class = MetamonPlayer
        elif battle_backend == "pokeagent":
            player_class = PokeAgentPlayer
        elif battle_backend == "pokepy":
            raise ValueError(
                "battle_backend='pokepy' is only supported via metamon.env.pokepy_battle "
                "(VectorizedPokepyEnv / BattlePokepyVectorized), not PokeEnvWrapper."
            )
        else:
            raise ValueError(
                f"Invalid battle backend: {battle_backend}. Options are "
                "'poke-env', 'metamon', 'pokeagent', or 'pokepy' (vectorized eval only)."
            )

        super().__init__(
            player_class=player_class,
            battle_format=battle_format,
            server_configuration=self.server_configuration,
            account_configuration=player_account_configuration,
            team=player_team_set,
            avatar=_check_avatar(player_avatar),
            start_timer_on_battle_start=start_timer_on_battle_start,
            start_challenging=start_challenging,
        )

        # Set team preview model on the agent if provided and using metamon backend
        if team_preview_model is not None and battle_backend == "metamon":
            self.agent.team_preview_model = team_preview_model

    @property
    def server_configuration(self):
        return LocalhostServerConfiguration

    def get_opponent(self):
        return self._current_opponent

    def action_space_size(self):
        return self.metamon_action_space.gym_space.n

    def on_invalid_order(self, battle: Battle):
        return self.choose_random_move(battle)

    def _battle_state(self, battle: Battle) -> UniversalState:
        return UniversalState.from_Battle(battle)

    def reset(self, *args, **kwargs):
        self.metamon_obs_space.reset()
        self.invalid_action_counter = 0
        self.valid_action_counter = 0
        self.turn_counter = 0
        self.battle_reference = self.agent.n_won_battles
        obs, info = super().reset(*args, **kwargs)
        self._most_recent_state = self._battle_state(self.current_battle)
        self._update_legal_actions(self._most_recent_state, self.current_battle)
        info["legal_actions"] = self._most_recent_legal_actions
        self.trajectory = {"states": [self._most_recent_state], "actions": []}
        return obs, info

    def action_to_move(self, action: Any, battle: Battle):
        universal_state = self._battle_state(battle)
        universal_action = self.metamon_action_space.agent_output_to_action(
            state=universal_state, agent_output=action
        )
        battle_order = universal_action.to_BattleOrder(battle)
        if battle_order is None:
            self.invalid_action_counter += 1
            return self.on_invalid_order(battle)
        else:
            self.valid_action_counter += 1
            return battle_order

    def describe_embedding(self) -> gym.spaces.Space:
        return self.metamon_obs_space.gym_space

    def calc_reward(self, last_battle: Battle, current_battle: Battle) -> float:
        last_state = self._battle_state(last_battle)
        state = self._battle_state(current_battle)
        reward = self.reward_function(last_state, state)
        return reward

    def _update_legal_actions(self, state: UniversalState, battle: Battle):
        legal_actions = UniversalAction.definitely_valid_actions(
            state=state, battle=battle
        )
        self._most_recent_legal_actions = [
            self.metamon_action_space.action_to_agent_output(state=state, action=action)
            for action in legal_actions
        ]
        return self._most_recent_legal_actions

    def embed_battle(self, battle: Battle):
        universal_state = self._battle_state(battle)
        self._most_recent_state = universal_state
        self._update_legal_actions(universal_state, battle)
        return self.metamon_obs_space.state_to_obs(universal_state)

    def step(self, action):
        self.turn_counter += 1
        next_obs, reward, terminated, truncated, info = super().step(action)
        info["legal_actions"] = self._most_recent_legal_actions
        if self.save_trajectories_to is not None:
            self.trajectory["states"].append(self._most_recent_state)
            self.trajectory["actions"].append(
                self.metamon_action_space.agent_output_to_action(
                    state=self._most_recent_state, agent_output=action
                ).action_idx
            )

        # enforce simple turn limit
        hit_time_limit = self.turn_counter > self.turn_limit
        terminated |= hit_time_limit
        truncated |= hit_time_limit
        if terminated or truncated:
            # logging info
            info["valid_action_count"] = self.valid_action_counter
            info["invalid_action_count"] = self.invalid_action_counter
            info["won"] = self.agent.n_won_battles > self.battle_reference
            self.battle_reference = self.agent.n_won_battles

            if (
                self.save_trajectories_to is not None
                or self.save_results_to is not None
            ):
                # build a long filename that matches the format of the parsed replay dataset
                result = "WIN" if info["won"] == 1 else "LOSS"
                # Use the actual Showdown battle ID to enable matching both perspectives
                # battle_tag format: "battle-gen1ou-12345" -> extract just the number
                showdown_battle_id = self.current_battle.battle_tag.split("-")[-1]
                battle_id = showdown_battle_id
                timestamp = datetime.now().strftime("%m-%d-%Y-%H:%M:%S")
                opponent_name = (
                    self.metamon_opponent_name or self.current_battle.opponent_username
                )

                if self.save_trajectories_to is not None:
                    filename = f"metamon-{self.metamon_battle_format}-{battle_id}_Unrated_{self.player_username}_vs_{opponent_name}_{timestamp}_{result}.json.lz4"
                    # matches the format of the parsed replay dataset
                    output_json = {
                        "states": [s.to_dict() for s in self.trajectory["states"]],
                        # NOTE: the replay parser leaves a blank (-1) final action; matched here
                        "actions": self.trajectory["actions"] + [-1],
                    }
                    # conservative file writing to avoid partial writes on shutdown or interruption
                    # when launching multiple environments in parallel
                    path = os.path.join(self.save_trajectories_to, filename)
                    temp_path = path + ".tmp"
                    with lz4.frame.open(temp_path, "wb") as f:
                        f.write(json.dumps(output_json).encode("utf-8"))
                    os.rename(temp_path, path)

                if self.save_results_to is not None:
                    with open(self.save_results_to, "a") as f:
                        f.write(
                            f"{self.player_username},{self.metamon_team_set.most_recent_team_file},{opponent_name},{result},{self.turn_counter},{battle_id}\n"
                        )

        return next_obs, reward, terminated, truncated, info

    def take_long_break(self):
        self.close(purge=False)
        self.reset_battles()

    def resume_from_break(self):
        self.start_challenging()


class BattleAgainstBaseline(PokeEnvWrapper):
    """
    Battle against a specified opponent.

    Can be used to battle any opponent that connects via the poke-env interface
    (e.g., any baseline in the `baselines` module, or any other custom `Player`)

    Assumes the player and opponent are both sampling from the same set of team files.
    """

    def __init__(
        self,
        battle_format: str,
        observation_space: ObservationSpace,
        action_space: ActionSpace,
        reward_function: RewardFunction,
        team_set: TeamSet,
        opponent_type: Type[Player],
        turn_limit: int = 200,
        save_trajectories_to: Optional[str] = None,
        save_results_to: Optional[str] = None,
        battle_backend: str = "poke-env",
        team_preview_model=None,
    ):
        super().__init__(
            battle_format=battle_format,
            observation_space=observation_space,
            action_space=action_space,
            reward_function=reward_function,
            player_team_set=team_set,
            opponent_team_set=team_set,
            opponent_type=opponent_type,
            team_preview_model=team_preview_model,
            turn_limit=turn_limit,
            save_trajectories_to=save_trajectories_to,
            save_results_to=save_results_to,
            battle_backend=battle_backend,
        )


class QueueOnLocalLadder(PokeEnvWrapper):
    """
    Battle against an opponent by queueing for ladder matches on the local server.

    Can be used to battle any opponent that plays with the Showdown API
    (e.g. humans, your own ML baselines, third-party heuristic bots, etc.).

    Create the environment, start laddering with the opponent, and the battle(s) will begin
    when both players are connected.
    """

    # increases time to launch opponent envs before ladder loop times out ("Agent is not challenging")
    # With sequential execution and 30s sleep, this gives ~167 seconds (1000 * 0.167s default retry time)
    _INIT_RETRIES = 2000

    def __init__(
        self,
        battle_format: str,
        num_battles: Optional[int],
        observation_space: ObservationSpace,
        action_space: ActionSpace,
        reward_function: RewardFunction,
        player_team_set: TeamSet,
        player_username: str,
        player_avatar: Optional[str] = None,
        start_timer_on_battle_start: bool = True,
        save_trajectories_to: Optional[str] = None,
        save_results_to: Optional[str] = None,
        player_password: Optional[str] = None,
        battle_backend: str = "poke-env",
        print_battle_bar: bool = True,
        team_preview_model=None,
    ):
        super().__init__(
            battle_format=battle_format,
            observation_space=observation_space,
            action_space=action_space,
            reward_function=reward_function,
            player_team_set=player_team_set,
            player_username=player_username,
            player_password=player_password,
            player_avatar=player_avatar,
            start_timer_on_battle_start=start_timer_on_battle_start,
            opponent_type=None,
            start_challenging=False,
            turn_limit=float("inf"),
            save_trajectories_to=save_trajectories_to,
            save_results_to=save_results_to,
            battle_backend=battle_backend,
            team_preview_model=team_preview_model,
        )
        print(f"Laddering for {num_battles} battles")
        self.print_battle_bar = print_battle_bar
        self.player_username = player_username
        self.player_password = player_password
        self.num_battles = num_battles
        self.handle_ladder_start(n_challenges=num_battles)

    def handle_ladder_start(self, n_challenges: int):
        # hook to allow throttling on pokeagent ladder
        return self.start_laddering(n_challenges=n_challenges)

    def step(self, action):
        next_state, reward, terminated, truncated, info = super().step(action)
        if self.print_battle_bar:
            self.render()
        return next_state, reward, terminated, truncated, info


class ChallengeByUsername(PokeEnvWrapper):
    """
    Battle against a specific opponent by sending/accepting challenges by username.

    Unlike QueueOnLocalLadder (random matchmaking via the ladder), this creates
    deterministic head-to-head matchups between two named players on the same server.
    Multiple such matchups can run simultaneously on the same server.

    One side must be the "challenger" (sends challenges) and the other the "acceptor"
    (accepts challenges). Both use the standard gymnasium env API for stepping through
    battles.

    Args:
        battle_format: The battle format (e.g. "gen1ou").
        num_battles: Number of battles to play.
        observation_space: The observation space.
        action_space: The action space.
        reward_function: The reward function.
        player_team_set: The team set for this player.
        player_username: This player's username.
        opponent_username: The opponent's username to challenge/accept from.
        role: "challenger" (sends challenges) or "acceptor" (accepts challenges).
        player_avatar: Optional avatar name.
        start_timer_on_battle_start: Whether to start the battle timer.
        save_trajectories_to: Directory to save trajectories.
        save_results_to: Directory to save per-battle result logs.
        battle_backend: Showdown state parsing backend.
        print_battle_bar: Whether to print battle status.
        team_preview_model: Optional team preview model.
    """

    _INIT_RETRIES = 1000

    def __init__(
        self,
        battle_format: str,
        num_battles: int,
        observation_space: ObservationSpace,
        action_space: ActionSpace,
        reward_function: RewardFunction,
        player_team_set: TeamSet,
        player_username: str,
        opponent_username: str,
        role: str = "challenger",
        player_avatar: Optional[str] = None,
        start_timer_on_battle_start: bool = True,
        save_trajectories_to: Optional[str] = None,
        save_results_to: Optional[str] = None,
        battle_backend: str = "metamon",
        print_battle_bar: bool = True,
        team_preview_model=None,
    ):
        assert role in (
            "challenger",
            "acceptor",
        ), f"role must be 'challenger' or 'acceptor', got '{role}'"
        self._opponent_username = opponent_username
        self._role = role

        super().__init__(
            battle_format=battle_format,
            observation_space=observation_space,
            action_space=action_space,
            reward_function=reward_function,
            player_team_set=player_team_set,
            player_username=player_username,
            player_avatar=player_avatar,
            start_timer_on_battle_start=start_timer_on_battle_start,
            opponent_type=None,
            start_challenging=False,
            turn_limit=float("inf"),
            save_trajectories_to=save_trajectories_to,
            save_results_to=save_results_to,
            battle_backend=battle_backend,
            team_preview_model=team_preview_model,
        )
        print(
            f"Challenge mode ({role}): {player_username} vs {opponent_username} "
            f"for {num_battles} battles"
        )
        self.print_battle_bar = print_battle_bar
        self.player_username = player_username
        self.num_battles = num_battles

        import asyncio
        from poke_env.concurrency import POKE_LOOP

        if role == "challenger":
            self.start_challenging(n_challenges=num_battles)
        else:
            self._challenge_task = asyncio.run_coroutine_threadsafe(
                self._accept_challenge_loop(num_battles), POKE_LOOP
            )

    def get_opponent(self):
        """Return opponent username so _challenge_loop sends challenges to them."""
        return self._opponent_username

    async def _accept_challenge_loop(self, n_challenges: int):
        """Accept loop that mirrors poke-env's _challenge_loop exactly.

        Accepts one challenge at a time and fully awaits the battle before
        accepting the next.  This keeps the gym-env observation/action queues
        in the same cadence as the challenger's send_challenges(opponent, 1)
        path, ensuring terminated/truncated signals propagate correctly.
        """
        for _ in range(n_challenges):
            await self.agent.accept_challenges(self._opponent_username, 1, None)

    def step(self, action):
        next_state, reward, terminated, truncated, info = super().step(action)
        if self.print_battle_bar:
            self.render()
        return next_state, reward, terminated, truncated, info


PokeAgentServerConfiguration = ServerConfiguration(
    "wss://battling.pokeagentchallenge.com/showdown/websocket",
    "https://battling.pokeagentchallenge.com/action.php?",
)


class PokeAgentLadder(QueueOnLocalLadder):
    """
    Battle against the PokéAgent Challenge Ladder (https://battling.pokeagentchallenge.com)
    """

    # increases time to launch opponent envs before ladder loop times out ("Agent is not challenging").
    _INIT_RETRIES = 3000

    @property
    def server_configuration(self):
        return PokeAgentServerConfiguration

    def handle_ladder_start(self, n_challenges: int):
        assert (
            self.player_username is not None and self.player_password is not None
        ), "Username and password are required for PokéAgent laddering"
        super().start_laddering(n_challenges)
